const GET_ERRORS = 'GET_ERRORS';
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const GET_PROFILE = "GET_PROFILE"
const PROFILE_NOT_FOUND = "PROFILE_NOT_FIND"
const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE"
const GET_PROFILES = "GET_PROFILES"
const PROFILE_LOADING = "PROFILE_LOADING"

const DELETE_POST = 'DELETE_POST';
const ADD_POST = 'ADD_POST'
const GET_POSTS = "GET_POSTS"
const GET_POST = "GET_POST"
const POST_LOADING = "POST_LOADING"
export {
    GET_ERRORS,
    SET_CURRENT_USER,
    GET_PROFILE,
    PROFILE_NOT_FOUND,
    CLEAR_CURRENT_PROFILE,
    GET_PROFILES,
    PROFILE_LOADING,
    DELETE_POST,
    ADD_POST,
    GET_POST,
    GET_POSTS,
    POST_LOADING
};